/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'date' : Time,
  'specialRequests' : IDL.Text,
  'numGuests' : IDL.Nat,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'submitReservation' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'date' : Time,
    'specialRequests' : IDL.Text,
    'numGuests' : IDL.Nat,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'submitReservation' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };